[project]
name = "webportal-client"
version = "0.5.0"
description = "Synchronous and asynchronous Python clients for the AQUARIUS WebPortal API."
readme = "README.md"
authors = [
    { name = "Jason Law", email = "jason.law@portlandoregon.gov" }
]
license = "MIT"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.26.0",
    "httpx>=0.23.0",
]

[project.optional-dependencies]
polars = [
    "polars>=1.36.1",
]
pandas = [
    "pandas>=2.3.3",
]

[build-system]
requires = ["uv_build>=0.11.0,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pydata-sphinx-theme>=0.16.1",
    "pytest>=8.4.2",
    "sphinx>=7.4.7",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
testpaths = ["tests"]
pythonpath = ["src"]
